package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// backendRoot is workspace/backend as seen from this package's directory,
// which is where `go test` runs it.
const backendRoot = "../.."

// TestGeneratedTypesAreCurrent fails when a Go struct on the API surface has
// changed without the frontend declarations being regenerated. CI runs
// `go test ./...`, so this is what stops the two from drifting apart.
func TestGeneratedTypesAreCurrent(t *testing.T) {
	want, err := generate(backendRoot)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	path := filepath.Join(backendRoot, filepath.FromSlash(outputPath))
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v\nrun `go run ./cmd/gentypes` from workspace/backend", path, err)
	}
	// A Windows checkout with autocrlf may hand us CRLF; the content is what matters.
	got = bytes.ReplaceAll(got, []byte("\r\n"), []byte("\n"))
	if !bytes.Equal(got, want) {
		t.Fatalf("%s is out of date with the Go structs (first difference: %s).\n"+
			"run `go run ./cmd/gentypes` from workspace/backend (or `npm run gen:types` from workspace/frontend) and commit the result",
			filepath.ToSlash(path), firstDiff(got, want))
	}
}

// TestMappingRules pins the encoding/json semantics the generator relies on,
// against the real models rather than a fixture that could drift from them.
func TestMappingRules(t *testing.T) {
	code, err := generate(backendRoot)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	out := string(code)
	for _, want := range []string{
		"// Code generated by cmd/gentypes. DO NOT EDIT.",
		// json tag name, pointer -> | null, no omitempty -> required
		"export interface TodoRecord {",
		"  thread_id: string | null;",
		// omitempty -> optional
		"  priority?: string;",
		"  due_date?: string | null;",
		// time.Time -> string
		"  created_at: string;",
		// untagged exported field keeps its Go name, as encoding/json does
		"export interface Workspace {",
		"  LastActivityAt: string;",
		// []byte -> unknown
		"  enabled_skills: unknown;",
		// cross-package reference and handler roots
		"  tasks: TodoRecord[];",
		"  run?: ParallelRunView | null;",
		"  lanes: ParallelLaneRecord[];",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated output is missing %q", want)
		}
	}
	for _, reject := range []string{
		"  Steps:",    // ChannelPipeline.Steps is json:"-"
		"  Baseline:", // AgentTurnChange.Baseline is json:"-"
		"interface laneDispatch",
	} {
		if strings.Contains(out, reject) {
			t.Errorf("generated output should not contain %q", reject)
		}
	}
}

func firstDiff(got, want []byte) string {
	gl := strings.Split(string(got), "\n")
	wl := strings.Split(string(want), "\n")
	for i := 0; i < len(gl) || i < len(wl); i++ {
		var g, w string
		if i < len(gl) {
			g = gl[i]
		}
		if i < len(wl) {
			w = wl[i]
		}
		if g != w {
			return fmt.Sprintf("line %d: have %q, want %q", i+1, g, w)
		}
	}
	return "none"
}
